### PR TITLE
refactor: reuse change addresses

### PR DESCRIPTION
**Pull request by gregdhill**
Signed-off-by: Gregory Hill <gregorydhill@outlook.com>

### CODE REVIEW

**Comment by sander2** [comment]
Can you remind me of the purpose of this PR again, i.e. what's the main motivation for this change? We had/have some other significant changes which impact this one: removal of theft checks and removal of `refund`. With these changes in mind, why do we want to remove arbitrary change addresses? The only advantage I see now is a reduction of storage bloat. Am I missing anything?

**Comment by gregdhill** [comment]
The original concern was related to theft reporting since allowing the registration of any address enabled the Vault to move funds without being reported. However, if it is agreed that theft reporting can be removed (as implemented in https://github.com/interlay/interbtc/pull/669) then you are right the only concern would be storage bloat. We do want to address that however and this change doesn't necessarily preclude us from keeping that extrinsic anyway.

**Comment by sander2** [comment]
Actually, if we remove theft reporting, we can also completely remove the address registration, and we don't need this change in the client - we can just keep the default bitcoin core behavior. That'll be slightly better privacy-wise and keeps the code as simple as possible. Of course, people can still analyze bitcoin transfers based on the redeem data, but it'll require customized tools

**Comment by gregdhill** [comment]
Agree, we can re-open if theft reporting is kept.

**Comment by gregdhill** [comment]
Agree, we can re-open if theft reporting is kept.

**Pull request closed without merging**
